/*
  Warnings:

  - You are about to drop the column `annualEnergy` on the `Calculations` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "Calculations" DROP COLUMN "annualEnergy",
ADD COLUMN     "annualKwhCoolingPTHP" DOUBLE PRECISION,
ADD COLUMN     "annualKwhHeatingPTHP" DOUBLE PRECISION,
ADD COLUMN     "annualKwhPTAC" DOUBLE PRECISION,
ADD COLUMN     "annualMMBtuPTAC" DOUBLE PRECISION,
ADD COLUMN     "annualMMBtuPTHP" DOUBLE PRECISION,
ADD COLUMN     "annualThermsPTAC" DOUBLE PRECISION,
ADD COLUMN     "coefficientOfPerformancePTHP" DOUBLE PRECISION NOT NULL DEFAULT 3.5,
ADD COLUMN     "coolingHoursPerDay" INTEGER NOT NULL DEFAULT 7,
ADD COLUMN     "coolingMMBtuPTAC" DOUBLE PRECISION,
ADD COLUMN     "coolingMMBtuPTHP" DOUBLE PRECISION,
ADD COLUMN     "dailyKwhCoolingPTHP" DOUBLE PRECISION,
ADD COLUMN     "dailyKwhHeatingPTHP" DOUBLE PRECISION,
ADD COLUMN     "daysCool" INTEGER NOT NULL DEFAULT 117,
ADD COLUMN     "daysHeat" INTEGER NOT NULL DEFAULT 248,
ADD COLUMN     "energyReductionPercentagePTHP" DOUBLE PRECISION,
ADD COLUMN     "heatingHoursPerDay" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN     "heatingMMBtuPTAC" DOUBLE PRECISION,
ADD COLUMN     "heatingMMBtuPTHP" DOUBLE PRECISION,
ADD COLUMN     "kwhPerUnitPerHourPTAC" DOUBLE PRECISION NOT NULL DEFAULT 1.25,
ADD COLUMN     "kwhPerUnitPerHourPTHP" DOUBLE PRECISION NOT NULL DEFAULT 1.25,
ADD COLUMN     "thermsPerUnitPerHour" DOUBLE PRECISION NOT NULL DEFAULT 0.05,
ADD COLUMN     "totalAnnualKwhPTHP" DOUBLE PRECISION;
