#!/bin/bash

# Script to compile LaTeX reports generated by the API
# Usage: ./scripts/compile-latex-report.sh <latex-file> [output-dir]

set -e  # Exit on any error

# Function to display usage
usage() {
    echo "Usage: $0 <latex-file> [output-dir]"
    echo ""
    echo "Arguments:"
    echo "  latex-file    Path to the LaTeX file to compile"
    echo "  output-dir    Output directory for PDF (optional, defaults to same directory as LaTeX file)"
    echo ""
    echo "Examples:"
    echo "  $0 building-report-123MainSt.tex"
    echo "  $0 building-report-123MainSt.tex ./reports/"
    echo ""
    echo "Requirements:"
    echo "  - LuaLaTeX must be installed (part of TeX Live or BasicTeX)"
    echo "  - LaTeX file must be generated from /api/calculations/{id}/latex-report endpoint"
}

# Check arguments
if [ $# -lt 1 ]; then
    echo "Error: Missing required arguments"
    usage
    exit 1
fi

LATEX_FILE="$1"
OUTPUT_DIR="${2:-$(dirname "$LATEX_FILE")}"

# Validate LaTeX file exists
if [ ! -f "$LATEX_FILE" ]; then
    echo "Error: LaTeX file '$LATEX_FILE' not found"
    exit 1
fi

# Get absolute paths
LATEX_FILE_ABS=$(realpath "$LATEX_FILE")
OUTPUT_DIR_ABS=$(realpath "$OUTPUT_DIR")
LATEX_DIR=$(dirname "$LATEX_FILE_ABS")
LATEX_NAME=$(basename "$LATEX_FILE_ABS" .tex)

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR_ABS"

# Check if LuaLaTeX is available
if ! command -v lualatex &> /dev/null; then
    echo "Error: lualatex command not found"
    echo ""
    echo "Please install LaTeX with LuaLaTeX support:"
    echo "  macOS: brew install --cask basictex"
    echo "  Linux: sudo apt-get install texlive-full"
    echo ""
    echo "After installation, you may need to install additional packages:"
    echo "  sudo tlmgr install pgfplots tikz amsmath booktabs siunitx"
    exit 1
fi

echo "Compiling LaTeX report..."
echo "Input: $LATEX_FILE_ABS"
echo "Output: $OUTPUT_DIR_ABS/${LATEX_NAME}.pdf"
echo ""

# Change to the LaTeX file directory for compilation
cd "$LATEX_DIR"

# Compile with LuaLaTeX (run twice for proper references)
echo "Running LuaLaTeX (first pass)..."
lualatex -interaction=nonstopmode -output-directory="$OUTPUT_DIR_ABS" "$LATEX_FILE_ABS"

echo "Running LuaLaTeX (second pass)..."
lualatex -interaction=nonstopmode -output-directory="$OUTPUT_DIR_ABS" "$LATEX_FILE_ABS"

# Check if PDF was created successfully
PDF_FILE="$OUTPUT_DIR_ABS/${LATEX_NAME}.pdf"
if [ -f "$PDF_FILE" ]; then
    echo ""
    echo "✅ LaTeX compilation successful!"
    echo "PDF created: $PDF_FILE"
    
    # Clean up auxiliary files
    echo "Cleaning up auxiliary files..."
    rm -f "$OUTPUT_DIR_ABS/${LATEX_NAME}.aux"
    rm -f "$OUTPUT_DIR_ABS/${LATEX_NAME}.log"
    rm -f "$OUTPUT_DIR_ABS/${LATEX_NAME}.out"
    rm -f "$OUTPUT_DIR_ABS/${LATEX_NAME}.toc"
    rm -f "$OUTPUT_DIR_ABS/${LATEX_NAME}.fls"
    rm -f "$OUTPUT_DIR_ABS/${LATEX_NAME}.fdb_latexmk"
    
    # Optionally open the PDF (macOS only)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        read -p "Open PDF in default viewer? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            open "$PDF_FILE"
        fi
    fi
else
    echo ""
    echo "❌ LaTeX compilation failed!"
    echo "Check the log file for errors: $OUTPUT_DIR_ABS/${LATEX_NAME}.log"
    exit 1
fi