import React from 'react'
import { CalculationResult } from '@/types/calculation-result-type'
import CollapsibleSection from '@/components/shared/CollapsibleSection'

const AiAnalysisNotes = ({ c }: { c: CalculationResult }) => {
  // Don't render if no AI analysis notes
  if (!c.aiAnalysisNotes || c.aiAnalysisNotes.trim() === '') {
    return null;
  }

  return (
    <CollapsibleSection
      title="AI Building Analysis"
      defaultOpen={false}
      className="w-full mx-auto shadow-lg"
    >
      <div className="space-y-4">
        {/* AI Badge */}
        <div className="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 w-fit bg-blue-500/10 text-blue-500 border-blue-500/20">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mr-1.5">
            <path d="M12 8V4H8"/>
            <rect width="16" height="12" x="4" y="8" rx="2"/>
            <path d="M2 14h2"/>
            <path d="M20 14h2"/>
            <path d="M15 13v2"/>
            <path d="M9 13v2"/>
          </svg>
          AI Generated Analysis
        </div>

        {/* Analysis Content */}
        <div className="bg-gray-50 dark:bg-gray-800 p-4 rounded-lg">
          <div className="prose prose-sm max-w-none dark:prose-invert">
            <div className="whitespace-pre-wrap text-gray-700 dark:text-gray-300">
              {c.aiAnalysisNotes}
            </div>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="text-xs text-gray-500 dark:text-gray-400 italic">
          This analysis was generated by AI based on building characteristics and should be reviewed by qualified professionals.
        </div>
      </div>
    </CollapsibleSection>
  )
}

export default AiAnalysisNotes